#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qldoansvhutech.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyDoAn")]
	public partial class QLDADataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    partial void InsertBaocao(Baocao instance);
    partial void UpdateBaocao(Baocao instance);
    partial void DeleteBaocao(Baocao instance);
    partial void InsertCongviectuan(Congviectuan instance);
    partial void UpdateCongviectuan(Congviectuan instance);
    partial void DeleteCongviectuan(Congviectuan instance);
    partial void InsertDoan(Doan instance);
    partial void UpdateDoan(Doan instance);
    partial void DeleteDoan(Doan instance);
    partial void InsertGvhd(Gvhd instance);
    partial void UpdateGvhd(Gvhd instance);
    partial void DeleteGvhd(Gvhd instance);
    partial void InsertLoaiDA(LoaiDA instance);
    partial void UpdateLoaiDA(LoaiDA instance);
    partial void DeleteLoaiDA(LoaiDA instance);
    partial void InsertSinhvien(Sinhvien instance);
    partial void UpdateSinhvien(Sinhvien instance);
    partial void DeleteSinhvien(Sinhvien instance);
    #endregion
		
		public QLDADataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QuanLyDoAnConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLDADataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDADataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDADataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDADataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<Baocao> Baocaos
		{
			get
			{
				return this.GetTable<Baocao>();
			}
		}
		
		public System.Data.Linq.Table<Congviectuan> Congviectuans
		{
			get
			{
				return this.GetTable<Congviectuan>();
			}
		}
		
		public System.Data.Linq.Table<Doan> Doans
		{
			get
			{
				return this.GetTable<Doan>();
			}
		}
		
		public System.Data.Linq.Table<Gvhd> Gvhds
		{
			get
			{
				return this.GetTable<Gvhd>();
			}
		}
		
		public System.Data.Linq.Table<LoaiDA> LoaiDAs
		{
			get
			{
				return this.GetTable<LoaiDA>();
			}
		}
		
		public System.Data.Linq.Table<Role> Roles
		{
			get
			{
				return this.GetTable<Role>();
			}
		}
		
		public System.Data.Linq.Table<Sinhvien> Sinhviens
		{
			get
			{
				return this.GetTable<Sinhvien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Taikhoan;
		
		private string _Matkhau;
		
		private System.Nullable<int> _Role;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTaikhoanChanging(string value);
    partial void OnTaikhoanChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnRoleChanging(System.Nullable<int> value);
    partial void OnRoleChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan", DbType="VarChar(50)")]
		public string Taikhoan
		{
			get
			{
				return this._Taikhoan;
			}
			set
			{
				if ((this._Taikhoan != value))
				{
					this.OnTaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan = value;
					this.SendPropertyChanged("Taikhoan");
					this.OnTaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="VarChar(32)")]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="Int")]
		public System.Nullable<int> Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Baocao")]
	public partial class Baocao : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Url;
		
		private string _Ghichu;
		
		private System.Nullable<int> _Id_da;
		
		private EntityRef<Doan> _Doan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnGhichuChanging(string value);
    partial void OnGhichuChanged();
    partial void OnId_daChanging(System.Nullable<int> value);
    partial void OnId_daChanged();
    #endregion
		
		public Baocao()
		{
			this._Doan = default(EntityRef<Doan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(MAX)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghichu", DbType="NVarChar(MAX)")]
		public string Ghichu
		{
			get
			{
				return this._Ghichu;
			}
			set
			{
				if ((this._Ghichu != value))
				{
					this.OnGhichuChanging(value);
					this.SendPropertyChanging();
					this._Ghichu = value;
					this.SendPropertyChanged("Ghichu");
					this.OnGhichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_da", DbType="Int")]
		public System.Nullable<int> Id_da
		{
			get
			{
				return this._Id_da;
			}
			set
			{
				if ((this._Id_da != value))
				{
					if (this._Doan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_daChanging(value);
					this.SendPropertyChanging();
					this._Id_da = value;
					this.SendPropertyChanged("Id_da");
					this.OnId_daChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Doan_Baocao", Storage="_Doan", ThisKey="Id_da", OtherKey="Id", IsForeignKey=true)]
		public Doan Doan
		{
			get
			{
				return this._Doan.Entity;
			}
			set
			{
				Doan previousValue = this._Doan.Entity;
				if (((previousValue != value) 
							|| (this._Doan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Doan.Entity = null;
						previousValue.Baocaos.Remove(this);
					}
					this._Doan.Entity = value;
					if ((value != null))
					{
						value.Baocaos.Add(this);
						this._Id_da = value.Id;
					}
					else
					{
						this._Id_da = default(Nullable<int>);
					}
					this.SendPropertyChanged("Doan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Congviectuan")]
	public partial class Congviectuan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Mota;
		
		private string _url;
		
		private System.Nullable<int> _Id_gv;
		
		private System.Nullable<System.DateTime> _NgayBD;
		
		private System.Nullable<System.DateTime> _NgayKT;
		
		private System.Nullable<int> _Id_da;
		
		private System.Nullable<int> _Id_sv;
		
		private string _Tuan;
		
		private EntitySet<Doan> _Doans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void OnId_gvChanging(System.Nullable<int> value);
    partial void OnId_gvChanged();
    partial void OnNgayBDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBDChanged();
    partial void OnNgayKTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKTChanged();
    partial void OnId_daChanging(System.Nullable<int> value);
    partial void OnId_daChanged();
    partial void OnId_svChanging(System.Nullable<int> value);
    partial void OnId_svChanged();
    partial void OnTuanChanging(string value);
    partial void OnTuanChanged();
    #endregion
		
		public Congviectuan()
		{
			this._Doans = new EntitySet<Doan>(new Action<Doan>(this.attach_Doans), new Action<Doan>(this.detach_Doans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(MAX)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="NVarChar(MAX)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_gv", DbType="Int")]
		public System.Nullable<int> Id_gv
		{
			get
			{
				return this._Id_gv;
			}
			set
			{
				if ((this._Id_gv != value))
				{
					this.OnId_gvChanging(value);
					this.SendPropertyChanging();
					this._Id_gv = value;
					this.SendPropertyChanged("Id_gv");
					this.OnId_gvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBD", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayBD
		{
			get
			{
				return this._NgayBD;
			}
			set
			{
				if ((this._NgayBD != value))
				{
					this.OnNgayBDChanging(value);
					this.SendPropertyChanging();
					this._NgayBD = value;
					this.SendPropertyChanged("NgayBD");
					this.OnNgayBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKT", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayKT
		{
			get
			{
				return this._NgayKT;
			}
			set
			{
				if ((this._NgayKT != value))
				{
					this.OnNgayKTChanging(value);
					this.SendPropertyChanging();
					this._NgayKT = value;
					this.SendPropertyChanged("NgayKT");
					this.OnNgayKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_da", DbType="Int")]
		public System.Nullable<int> Id_da
		{
			get
			{
				return this._Id_da;
			}
			set
			{
				if ((this._Id_da != value))
				{
					this.OnId_daChanging(value);
					this.SendPropertyChanging();
					this._Id_da = value;
					this.SendPropertyChanged("Id_da");
					this.OnId_daChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_sv", DbType="Int")]
		public System.Nullable<int> Id_sv
		{
			get
			{
				return this._Id_sv;
			}
			set
			{
				if ((this._Id_sv != value))
				{
					this.OnId_svChanging(value);
					this.SendPropertyChanging();
					this._Id_sv = value;
					this.SendPropertyChanged("Id_sv");
					this.OnId_svChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuan", DbType="NVarChar(20)")]
		public string Tuan
		{
			get
			{
				return this._Tuan;
			}
			set
			{
				if ((this._Tuan != value))
				{
					this.OnTuanChanging(value);
					this.SendPropertyChanging();
					this._Tuan = value;
					this.SendPropertyChanged("Tuan");
					this.OnTuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Congviectuan_Doan", Storage="_Doans", ThisKey="Id", OtherKey="Id_cv")]
		public EntitySet<Doan> Doans
		{
			get
			{
				return this._Doans;
			}
			set
			{
				this._Doans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Doans(Doan entity)
		{
			this.SendPropertyChanging();
			entity.Congviectuan = this;
		}
		
		private void detach_Doans(Doan entity)
		{
			this.SendPropertyChanging();
			entity.Congviectuan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Doan")]
	public partial class Doan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Tenda;
		
		private string _Mota;
		
		private System.Nullable<int> _Id_gv;
		
		private System.Nullable<int> _Id_sv;
		
		private System.Nullable<int> _Id_lda;
		
		private System.Nullable<int> _Id_cv;
		
		private System.Nullable<bool> _Trangthai;
		
		private EntitySet<Baocao> _Baocaos;
		
		private EntityRef<Congviectuan> _Congviectuan;
		
		private EntityRef<LoaiDA> _LoaiDA;
		
		private EntityRef<Sinhvien> _Sinhvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTendaChanging(string value);
    partial void OnTendaChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    partial void OnId_gvChanging(System.Nullable<int> value);
    partial void OnId_gvChanged();
    partial void OnId_svChanging(System.Nullable<int> value);
    partial void OnId_svChanged();
    partial void OnId_ldaChanging(System.Nullable<int> value);
    partial void OnId_ldaChanged();
    partial void OnId_cvChanging(System.Nullable<int> value);
    partial void OnId_cvChanged();
    partial void OnTrangthaiChanging(System.Nullable<bool> value);
    partial void OnTrangthaiChanged();
    #endregion
		
		public Doan()
		{
			this._Baocaos = new EntitySet<Baocao>(new Action<Baocao>(this.attach_Baocaos), new Action<Baocao>(this.detach_Baocaos));
			this._Congviectuan = default(EntityRef<Congviectuan>);
			this._LoaiDA = default(EntityRef<LoaiDA>);
			this._Sinhvien = default(EntityRef<Sinhvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenda", DbType="NVarChar(50)")]
		public string Tenda
		{
			get
			{
				return this._Tenda;
			}
			set
			{
				if ((this._Tenda != value))
				{
					this.OnTendaChanging(value);
					this.SendPropertyChanging();
					this._Tenda = value;
					this.SendPropertyChanged("Tenda");
					this.OnTendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(MAX)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_gv", DbType="Int")]
		public System.Nullable<int> Id_gv
		{
			get
			{
				return this._Id_gv;
			}
			set
			{
				if ((this._Id_gv != value))
				{
					this.OnId_gvChanging(value);
					this.SendPropertyChanging();
					this._Id_gv = value;
					this.SendPropertyChanged("Id_gv");
					this.OnId_gvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_sv", DbType="Int")]
		public System.Nullable<int> Id_sv
		{
			get
			{
				return this._Id_sv;
			}
			set
			{
				if ((this._Id_sv != value))
				{
					if (this._Sinhvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_svChanging(value);
					this.SendPropertyChanging();
					this._Id_sv = value;
					this.SendPropertyChanged("Id_sv");
					this.OnId_svChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_lda", DbType="Int")]
		public System.Nullable<int> Id_lda
		{
			get
			{
				return this._Id_lda;
			}
			set
			{
				if ((this._Id_lda != value))
				{
					if (this._LoaiDA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_ldaChanging(value);
					this.SendPropertyChanging();
					this._Id_lda = value;
					this.SendPropertyChanged("Id_lda");
					this.OnId_ldaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_cv", DbType="Int")]
		public System.Nullable<int> Id_cv
		{
			get
			{
				return this._Id_cv;
			}
			set
			{
				if ((this._Id_cv != value))
				{
					if (this._Congviectuan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_cvChanging(value);
					this.SendPropertyChanging();
					this._Id_cv = value;
					this.SendPropertyChanged("Id_cv");
					this.OnId_cvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai", DbType="Bit")]
		public System.Nullable<bool> Trangthai
		{
			get
			{
				return this._Trangthai;
			}
			set
			{
				if ((this._Trangthai != value))
				{
					this.OnTrangthaiChanging(value);
					this.SendPropertyChanging();
					this._Trangthai = value;
					this.SendPropertyChanged("Trangthai");
					this.OnTrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Doan_Baocao", Storage="_Baocaos", ThisKey="Id", OtherKey="Id_da")]
		public EntitySet<Baocao> Baocaos
		{
			get
			{
				return this._Baocaos;
			}
			set
			{
				this._Baocaos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Congviectuan_Doan", Storage="_Congviectuan", ThisKey="Id_cv", OtherKey="Id", IsForeignKey=true)]
		public Congviectuan Congviectuan
		{
			get
			{
				return this._Congviectuan.Entity;
			}
			set
			{
				Congviectuan previousValue = this._Congviectuan.Entity;
				if (((previousValue != value) 
							|| (this._Congviectuan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Congviectuan.Entity = null;
						previousValue.Doans.Remove(this);
					}
					this._Congviectuan.Entity = value;
					if ((value != null))
					{
						value.Doans.Add(this);
						this._Id_cv = value.Id;
					}
					else
					{
						this._Id_cv = default(Nullable<int>);
					}
					this.SendPropertyChanged("Congviectuan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiDA_Doan", Storage="_LoaiDA", ThisKey="Id_lda", OtherKey="Id", IsForeignKey=true)]
		public LoaiDA LoaiDA
		{
			get
			{
				return this._LoaiDA.Entity;
			}
			set
			{
				LoaiDA previousValue = this._LoaiDA.Entity;
				if (((previousValue != value) 
							|| (this._LoaiDA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiDA.Entity = null;
						previousValue.Doans.Remove(this);
					}
					this._LoaiDA.Entity = value;
					if ((value != null))
					{
						value.Doans.Add(this);
						this._Id_lda = value.Id;
					}
					else
					{
						this._Id_lda = default(Nullable<int>);
					}
					this.SendPropertyChanged("LoaiDA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sinhvien_Doan", Storage="_Sinhvien", ThisKey="Id_sv", OtherKey="Id", IsForeignKey=true)]
		public Sinhvien Sinhvien
		{
			get
			{
				return this._Sinhvien.Entity;
			}
			set
			{
				Sinhvien previousValue = this._Sinhvien.Entity;
				if (((previousValue != value) 
							|| (this._Sinhvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sinhvien.Entity = null;
						previousValue.Doans.Remove(this);
					}
					this._Sinhvien.Entity = value;
					if ((value != null))
					{
						value.Doans.Add(this);
						this._Id_sv = value.Id;
					}
					else
					{
						this._Id_sv = default(Nullable<int>);
					}
					this.SendPropertyChanged("Sinhvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Baocaos(Baocao entity)
		{
			this.SendPropertyChanging();
			entity.Doan = this;
		}
		
		private void detach_Baocaos(Baocao entity)
		{
			this.SendPropertyChanging();
			entity.Doan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gvhd")]
	public partial class Gvhd : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Taikhoan;
		
		private string _Matkhau;
		
		private string _Hoten;
		
		private string _Email;
		
		private string _Sdt;
		
		private string _Hinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private EntitySet<Sinhvien> _Sinhviens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTaikhoanChanging(string value);
    partial void OnTaikhoanChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSdtChanging(string value);
    partial void OnSdtChanged();
    partial void OnHinhChanging(string value);
    partial void OnHinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    #endregion
		
		public Gvhd()
		{
			this._Sinhviens = new EntitySet<Sinhvien>(new Action<Sinhvien>(this.attach_Sinhviens), new Action<Sinhvien>(this.detach_Sinhviens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Taikhoan
		{
			get
			{
				return this._Taikhoan;
			}
			set
			{
				if ((this._Taikhoan != value))
				{
					this.OnTaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan = value;
					this.SendPropertyChanged("Taikhoan");
					this.OnTaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="VarChar(32)")]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(150)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="NChar(20)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this.OnSdtChanging(value);
					this.SendPropertyChanging();
					this._Sdt = value;
					this.SendPropertyChanged("Sdt");
					this.OnSdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh", DbType="NVarChar(MAX)")]
		public string Hinh
		{
			get
			{
				return this._Hinh;
			}
			set
			{
				if ((this._Hinh != value))
				{
					this.OnHinhChanging(value);
					this.SendPropertyChanging();
					this._Hinh = value;
					this.SendPropertyChanged("Hinh");
					this.OnHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gvhd_Sinhvien", Storage="_Sinhviens", ThisKey="Id", OtherKey="Id_gv")]
		public EntitySet<Sinhvien> Sinhviens
		{
			get
			{
				return this._Sinhviens;
			}
			set
			{
				this._Sinhviens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Sinhviens(Sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.Gvhd = this;
		}
		
		private void detach_Sinhviens(Sinhvien entity)
		{
			this.SendPropertyChanging();
			entity.Gvhd = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiDA")]
	public partial class LoaiDA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Tenloai;
		
		private EntitySet<Doan> _Doans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTenloaiChanging(string value);
    partial void OnTenloaiChanged();
    #endregion
		
		public LoaiDA()
		{
			this._Doans = new EntitySet<Doan>(new Action<Doan>(this.attach_Doans), new Action<Doan>(this.detach_Doans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenloai", DbType="NVarChar(50)")]
		public string Tenloai
		{
			get
			{
				return this._Tenloai;
			}
			set
			{
				if ((this._Tenloai != value))
				{
					this.OnTenloaiChanging(value);
					this.SendPropertyChanging();
					this._Tenloai = value;
					this.SendPropertyChanged("Tenloai");
					this.OnTenloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiDA_Doan", Storage="_Doans", ThisKey="Id", OtherKey="Id_lda")]
		public EntitySet<Doan> Doans
		{
			get
			{
				return this._Doans;
			}
			set
			{
				this._Doans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Doans(Doan entity)
		{
			this.SendPropertyChanging();
			entity.LoaiDA = this;
		}
		
		private void detach_Doans(Doan entity)
		{
			this.SendPropertyChanging();
			entity.LoaiDA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Role")]
	public partial class Role
	{
		
		private int _MaRole;
		
		private string _TenRole;
		
		public Role()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaRole", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int MaRole
		{
			get
			{
				return this._MaRole;
			}
			set
			{
				if ((this._MaRole != value))
				{
					this._MaRole = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenRole", DbType="NVarChar(50)")]
		public string TenRole
		{
			get
			{
				return this._TenRole;
			}
			set
			{
				if ((this._TenRole != value))
				{
					this._TenRole = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sinhvien")]
	public partial class Sinhvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _STT;
		
		private string _Hoten;
		
		private string _Matkhau;
		
		private string _Email;
		
		private System.Nullable<bool> _Gioitinh;
		
		private string _Taikhoan;
		
		private string _Sdt;
		
		private string _Hinh;
		
		private string _Lop;
		
		private System.Nullable<int> _Id_gv;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private EntitySet<Doan> _Doans;
		
		private EntityRef<Gvhd> _Gvhd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnGioitinhChanging(System.Nullable<bool> value);
    partial void OnGioitinhChanged();
    partial void OnTaikhoanChanging(string value);
    partial void OnTaikhoanChanged();
    partial void OnSdtChanging(string value);
    partial void OnSdtChanged();
    partial void OnHinhChanging(string value);
    partial void OnHinhChanged();
    partial void OnLopChanging(string value);
    partial void OnLopChanged();
    partial void OnId_gvChanging(System.Nullable<int> value);
    partial void OnId_gvChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    #endregion
		
		public Sinhvien()
		{
			this._Doans = new EntitySet<Doan>(new Action<Doan>(this.attach_Doans), new Action<Doan>(this.detach_Doans));
			this._Gvhd = default(EntityRef<Gvhd>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="NVarChar(32)")]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="Bit")]
		public System.Nullable<bool> Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan", DbType="NChar(32)")]
		public string Taikhoan
		{
			get
			{
				return this._Taikhoan;
			}
			set
			{
				if ((this._Taikhoan != value))
				{
					this.OnTaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan = value;
					this.SendPropertyChanged("Taikhoan");
					this.OnTaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="VarChar(20)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this.OnSdtChanging(value);
					this.SendPropertyChanging();
					this._Sdt = value;
					this.SendPropertyChanged("Sdt");
					this.OnSdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh", DbType="NVarChar(50)")]
		public string Hinh
		{
			get
			{
				return this._Hinh;
			}
			set
			{
				if ((this._Hinh != value))
				{
					this.OnHinhChanging(value);
					this.SendPropertyChanging();
					this._Hinh = value;
					this.SendPropertyChanged("Hinh");
					this.OnHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lop", DbType="NChar(50)")]
		public string Lop
		{
			get
			{
				return this._Lop;
			}
			set
			{
				if ((this._Lop != value))
				{
					this.OnLopChanging(value);
					this.SendPropertyChanging();
					this._Lop = value;
					this.SendPropertyChanged("Lop");
					this.OnLopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_gv", DbType="Int")]
		public System.Nullable<int> Id_gv
		{
			get
			{
				return this._Id_gv;
			}
			set
			{
				if ((this._Id_gv != value))
				{
					if (this._Gvhd.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnId_gvChanging(value);
					this.SendPropertyChanging();
					this._Id_gv = value;
					this.SendPropertyChanged("Id_gv");
					this.OnId_gvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sinhvien_Doan", Storage="_Doans", ThisKey="Id", OtherKey="Id_sv")]
		public EntitySet<Doan> Doans
		{
			get
			{
				return this._Doans;
			}
			set
			{
				this._Doans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Gvhd_Sinhvien", Storage="_Gvhd", ThisKey="Id_gv", OtherKey="Id", IsForeignKey=true)]
		public Gvhd Gvhd
		{
			get
			{
				return this._Gvhd.Entity;
			}
			set
			{
				Gvhd previousValue = this._Gvhd.Entity;
				if (((previousValue != value) 
							|| (this._Gvhd.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Gvhd.Entity = null;
						previousValue.Sinhviens.Remove(this);
					}
					this._Gvhd.Entity = value;
					if ((value != null))
					{
						value.Sinhviens.Add(this);
						this._Id_gv = value.Id;
					}
					else
					{
						this._Id_gv = default(Nullable<int>);
					}
					this.SendPropertyChanged("Gvhd");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Doans(Doan entity)
		{
			this.SendPropertyChanging();
			entity.Sinhvien = this;
		}
		
		private void detach_Doans(Doan entity)
		{
			this.SendPropertyChanging();
			entity.Sinhvien = null;
		}
	}
}
#pragma warning restore 1591
